### ISSUE TITLE
Cannot update a component (`LayerContextProvider`) while rendering a different component (`Frame`)

### ISSUE THREAD

**Issue by addlistener** [prevwong/craft.js#668]
**Describe the bug**
```
next-dev.js:20 Warning: Cannot update a component (`LayerContextProvider`) while rendering a different component (`Frame`). To locate the bad setState() call inside `Frame`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render
    at Frame (webpack-internal:///../../packages/core/dist/esm/index.js:510:18)
    at div
    at Content (webpack-internal:///../../node_modules/react-frame-component/lib/Content.js:30:5)
    at iframe
    at Frame (webpack-internal:///../../node_modules/react-frame-component/lib/Frame.js:46:5)
    at div
    at div
    at div
    at Viewport (webpack-internal:///./components/editor/Viewport/index.tsx:26:11)
    at Events (webpack-internal:///../../packages/core/dist/esm/index.js:2345:19)
    at Editor (webpack-internal:///../../packages/core/dist/esm/index.js:2436:19)
```

**To Reproduce**
Still working on it. Update later

**Expected behavior**
No warning

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| craft.js         |  46eb68e
| React            | 18.2.0
| TypeScript       | typescript@4.9.5
| Browser          | Version 126.0.6478.127 (Official Build) (x86_64)
| npm/Yarn         | 3.6.3
| Operating System | Darwin 23.0.0 Darwin Kernel Version 23.0.0: Fri Sep 15 14:42:42 PDT 2023; root:xnu-10002.1.13~1/RELEASE_X86_64 x86_64

**Comment by Traveller23** [comment]
https://github.com/prevwong/craft.js/blob/46eb68ef54a036f06c9433ee74b2359a8f38c610/packages/core/src/nodes/Element.tsx#L45-L72

The changes in [feat: SSR support](https://github.com/prevwong/craft.js/pull/637) also led to a problem being exposed:
When a component containing `craft.js`'s Element is dragged onto the `Frame`, the console displays the following warning:

![1](https://github.com/user-attachments/assets/5466fc13-ba40-4ae6-8edb-e4b3c9411954)

> Warning: Cannot update a component (UiTree) while rendering a different component (Ce). To locate the bad setState() call inside Ce, follow the stack trace as described in https://reactjs.org/link/setstate-in-render

This warning doesn't seem to cause any problems, but it's annoying.
